In [1]:
import pandas as pd

file_path = r'D:\Aa中工互联\工作安排\英格索兰\data\processed_data.xlsx'
df = pd.read_excel(file_path)

# 获取瞬时流量

In [2]:
df.columns

Index(['时间', 'DQ200系统压力', 'AVS系统压力', 'DQ200累积流量', 'AVS累积流量'], dtype='object')

In [3]:
df['时间'].head()

0   2025-05-01 00:00:00
1   2025-05-01 00:00:05
2   2025-05-01 00:00:10
3   2025-05-01 00:00:15
4   2025-05-01 00:00:20
Name: 时间, dtype: datetime64[ns]

In [4]:
df = df.sort_values(by='时间')

In [5]:
# 对 'DQ200累积流量' 和 'AVS累积流量' 分别做一阶差分
df['DQ200差分值'] = df['DQ200累积流量'].diff()
df['AVS差分值'] = df['AVS累积流量'].diff()

In [6]:
df.head()

,时间,DQ200系统压力,AVS系统压力,DQ200累积流量,AVS累积流量,DQ200差分值,AVS差分值
0,2025-05-01 00:00:00,6.071,6.402,329084448.0,54116824,NaN,NaN
1,2025-05-01 00:00:05,6.070,6.400,329084448.0,54116832,0.0,8.0
2,2025-05-01 00:00:10,6.062,6.407,329084480.0,54116844,32.0,12.0
3,2025-05-01 00:00:15,6.061,6.406,329084480.0,54116844,0.0,0.0
4,2025-05-01 00:00:20,6.066,6.396,329084480.0,54116856,0.0,12.0

In [7]:
# 删除第一个NaN行（如果需要）
df.dropna(inplace=True)
df.head()

,时间,DQ200系统压力,AVS系统压力,DQ200累积流量,AVS累积流量,DQ200差分值,AVS差分值
1,2025-05-01 00:00:05,6.070,6.400,329084448.0,54116832,0.0,8.0
2,2025-05-01 00:00:10,6.062,6.407,329084480.0,54116844,32.0,12.0
3,2025-05-01 00:00:15,6.061,6.406,329084480.0,54116844,0.0,0.0
4,2025-05-01 00:00:20,6.066,6.396,329084480.0,54116856,0.0,12.0
5,2025-05-01 00:00:25,6.075,6.391,329084480.0,54116860,0.0,4.0

In [8]:
df['瞬时流量'] = df['DQ200差分值'] + df['AVS差分值']

In [9]:
df.head()

,时间,DQ200系统压力,AVS系统压力,DQ200累积流量,AVS累积流量,DQ200差分值,AVS差分值,瞬时流量
1,2025-05-01 00:00:05,6.070,6.400,329084448.0,54116832,0.0,8.0,8.0
2,2025-05-01 00:00:10,6.062,6.407,329084480.0,54116844,32.0,12.0,44.0
3,2025-05-01 00:00:15,6.061,6.406,329084480.0,54116844,0.0,0.0,0.0
4,2025-05-01 00:00:20,6.066,6.396,329084480.0,54116856,0.0,12.0,12.0
5,2025-05-01 00:00:25,6.075,6.391,329084480.0,54116860,0.0,4.0,4.0

In [10]:
df.to_excel('0瞬时流量.xlsx')